name: Deploy Infrastructure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/179681486053/locations/global/workloadIdentityPools/github-oidc-pool/providers/github-oidc-provider'
          service_account: 'cicd-gcp-service-account@cicd-gcp-424408.iam.gserviceaccount.com'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: cicd-gcp-424408
          export_default_credentials: true

      - name: Check GCP Authentication
        run: gcloud auth list

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform/modules/commons

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: ./terraform/modules/commons

      - name: Initialize Terraform for vendor
        run: terraform init
        working-directory: ./terraform/modules/vendor

      - name: Apply Terraform for vendor
        run: terraform apply -auto-approve
        working-directory: ./terraform/modules/vendor
